### ISSUE TITLE
报错：好像出错了，请稍后再试。

### ISSUE THREAD

**Issue by dqzboy** [zhujunsan/chatgpt-web#8]
大佬，现在提问就报错 好像出错了，请稍后再试。使用的是AccessToken
![image](https://github.com/zhujunsan/chatgpt-web/assets/42825450/f1a2cba4-7b46-4df5-aba0-3ff936a6f487)

**Comment by dqzboy** [comment]
好像是官方3.5也需要验证了
https://github.com/zhile-io/pandora/issues/235#issuecomment-1774544557

**Comment by zhujunsan** [comment]
这个 repo 只会处理走 API 的问题，AccessToken 的没精力弄

**Comment by dqzboy** [comment]
Token的话自己部署个代理就行，这个倒是没事；就是这个提示信息一下子不知道是官方问题还是我这边问题，哈哈哈
